### PR TITLE
Fix ember-getowner-polyfill deprecation

### PR DESCRIPTION
**Pull request by krasnoukhov**
Related to #34

### CODE REVIEW

**Comment by briangonzalez** [comment]
@krasnoukhov Can this one be closed?

**Comment by krasnoukhov** [comment]
@briangonzalez This fixes a depecation warning, so it would be nice if you can merge it!

**Comment by krasnoukhov** [comment]
Thanks @briangonzalez!

**Comment by briangonzalez** [comment]
No, no, thanks you @krasnoukhov !

**Comment by briangonzalez** [comment]
0.1.1 released! https://www.npmjs.com/package/ember-router-scroll

**Pull request merged**
