### PR TITLE
Fix edge cases for URLs with anchors

### LINKED ISSUE #88: Error when navigating to url with nothing after anchor #
We're seeing a `Cannot read property 'offsetLeft' of null` error when navigating to a url with a trailing hash (e.g. http://example.com/home#). 

Looks to me like the culprit is this line here https://github.com/dollarshaveclub/ember-router-scroll/blob/master/addon/index.js#L38, as we're hitting that `if` condition even though there's nothing to be assigned to `hashElement`.

### PR DESCRIPTION
**Pull request by TerminalStar**
Fixes #88, handles both nothing after the anchor and IDs that don't match any elements in the page.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@TerminalStar I merged another PR which I think was somewhat related to this. Is this still necessary? If so, do you mind fixing the conflicts? Sorry about that 😞

**Comment by TerminalStar** [comment]
no worries - a quick glance makes me think it doesn't fix the same problem but i will take a proper look later today!

**Comment by TerminalStar** [comment]
@rwwagner90 looks like it is still a problem even with the other pr :( i've fixed the conflict so could you give this a look please?

**Comment by rwwagner90** [comment]
Looks good, thanks @TerminalStar! Just merged.

**Comment by YoranBrondsema** [comment]
Would it be possible to have a new release that includes this fix? It's adding quite a lot of noise to our error monitoring system. Thanks!

**Pull request merged**
