### PR TITLE
[BugFix] ensure correct intimate API is represented in transition mock

### PR DESCRIPTION
**Pull request by rondale-sc**

### CODE REVIEW

**Comment by rondale-sc** [comment]
@rwwagner90 @yowainwright I think this should address my previous PR.  If you aren't in a super rush I'll refactor this tomorrow to be a less ugly.  Unfortunately, I'm out of time for today.

**Comment by rwwagner90** [comment]
We need to revert this repo back a few commits before we merge anything else in. I'm unable to do it because pushing to master is disallowed.

**Comment by rwwagner90** [comment]
@rondale-sc I got the repo reverted back to where we want it. Is this ready to go? Needs a rebase to fix conflicts at least.

**Comment by rondale-sc** [comment]
@rwwagner90 I'll rebase in the next half hour or so and let you know.  I don't think it'll be that complicated.  Again, sorry for the bad PR earlier this week :(

**Comment by rondale-sc** [comment]
I pushed up the rebase.  But the registry situation needs to be resolved before CI will pass methinks.

**Comment by rwwagner90** [comment]
@rondale-sc yeah that seems odd. Would you mind just blowing away the yarn.lock and generating it again?

**Comment by rwwagner90** [comment]
Thanks so much @rondale-sc!

**Comment by willviles** [comment]
@rwwagner90 👋 fix is working great. Bump package version?

**Comment by rwwagner90** [comment]
@willviles I do not have permissions to npm. @yowainwright has to do the releases.

**Pull request merged**
