### PR TITLE
WIP - update app scheduler

### PR DESCRIPTION
**Pull request by snewcomer**
A WIP.  Will point when things seems stable or 1.0 is released.  Using it to test for now.

### CODE REVIEW

**Comment by scalvert** [comment]
@snewcomer I was literally just publishing the new app-scheduler, and am opening a PR to update it once that's done. Do you want me to just update this PR?

**Comment by snewcomer** [comment]
nice!  Thank you 🙏 I can update later today to save you the time of pulling down my branch.

**Comment by scalvert** [comment]
I have a branch ready with the changes. Would it be easier if I just opened that PR instead and we can close this one?

**Comment by snewcomer** [comment]
sure.  Sounds like there are some API updates?

**Comment by scalvert** [comment]
Yep. Basically the entire API has changed :). The surface area of the API wasn't large to start with, but now it's more explicit. Additionally, it doesn't use a bunch of threaded queuing and promises to achieve what we want. It's just using promises that are interleaved with rAF+macro tasks. It's also way more thoroughly tested.

**Comment by scalvert** [comment]
I have my branch working, and all the tests passing (with a few tweaks). Will be opening my PR soon.

**Pull request closed without merging**
