### PR TITLE
[update] adds git auto-tag script, nvmrc + fixes

### PR DESCRIPTION
**Pull request by yowainwright**
Fixes future issues like #133 🎉

### CODE REVIEW

**Comment by snewcomer** [comment]
Nice work!

**Comment by rwwagner90** [comment]
So this hook just runs after someone still manually runs `npm publish` right? We don't have anything automated around releasing, that I know of.

**Comment by yowainwright** [comment]
@rwwagner90 read the commit messages

**Comment by yowainwright** [comment]
Presumptuous behavior should not lead to more repository ownership. 

See the [code of conduct](https://github.com/dollarshaveclub/ember-router-scroll/blob/master/CODE_OF_CONDUCT.md#our-standards)

**Comment by rwwagner90** [comment]
It may be helpful for you to read that code of conduct as well. I've met a ton of resistance here for silly little things, for no reason. If DSC wants to solely maintain this, without community help, I'm all for that, but you may want to not stand in the way on every single thing otherwise. Please let me know your preference.

**Pull request merged**
