### PR TITLE
Upgrades ember-app-scheduler to 1.0.1

### PR DESCRIPTION
**Pull request by scalvert**
The first major release of ember-app-scheduler is out, and includes a rewrite of the existing API. This PR bumps the version to the latest, and upgrades the API usage to the new API.

This PR supersedes #129 and #138

### CODE REVIEW

**Comment by scalvert** [comment]
Also, @rwjblue

**Comment by scalvert** [comment]
For sure. Usually I let the library owners handle the bumping of the version etc. 

Glad it worked for you!

**Comment by scalvert** [comment]
Anything else I need to do to get this merged?

**Comment by snewcomer** [comment]
@scalvert I think once the version is bumped in the `package.json`, @yowainwright can merge && publish a new release if he approves.

Also @ryanto might be interested in this PR to try out.

https://github.com/dollarshaveclub/ember-router-scroll/pull/132#issuecomment-389228969

**Comment by scalvert** [comment]
Done!

**Comment by ryanto** [comment]
Thanks! This is working so far locally and in CI. 🎉 

From the readme I'm having some trouble understanding when I should and shouldn't use `delayScrollTop`? Seems like the answer would mostly be yes? Are there situations where I wouldn't want delayScrollTop...?

**Comment by snewcomer** [comment]
@ryanto I would say you don't want `delayScrollTop`.  Removing this as the default has now avoided any page flashes when transitioning b/w routes.  This was also seen in the dummy app...

https://github.com/dollarshaveclub/ember-router-scroll/pull/101

**Comment by ryanto** [comment]
Ah ok! Thanks

**Pull request merged**
