### PR TITLE
[version] major version bump 1.0.0

### PR DESCRIPTION
**Pull request by yowainwright**
# Version 1.0.0

> Follows important merges and great work by @rondale-sc @snewcomer @rwwagner90 

### Recent PRs reflecting lead-up to `1.0.0`

Listed below are a few PRs leading up to `1.0.0`.

- #127 
- #154 

\* Feel free to comment other important notes.

### CODE REVIEW

**Comment by snewcomer** [comment]
point3

**Comment by samselikoff** [comment]
Nice work everyone!

Are there any upgrade notes from 0.7 to 1.x? If so (or not) could we put them in CHANGELOG or on the Release?

**Comment by yowainwright** [comment]
@samselikoff @snewcomer there was debate on that. I'm happy to re-automate that—or someone else can. 😃

**Comment by snewcomer** [comment]
Changelog automation seems cool.  I'm not privy to the scripting changes to get this to work,  but if I remember right from a previous PR, it also came with a version bump or something like that.  If we could generate a changelog w/o a version bump, that would probably be cool.

**Comment by yowainwright** [comment]
Here's the [commit](https://github.com/dollarshaveclub/ember-router-scroll/commit/1efa8eecdca2c440544fcd425a4cc8ac386c78f8) to have what we had before.

**Comment by yowainwright** [comment]
@yowainwright @samselikoff how do you both feel about me re-adding that changelog update script?

**Comment by snewcomer** [comment]
So if I get this right, when you need to publish a patch, minor, or major release, you can run a command.  In doing so, it will create a changelog as well?  Can it only be configured to make a changelog on > minor releases? 

If not, I have always manually done it, but as Sam pointed out on another project, I forgot.  So I definitely see the value of this.  However, I just want to make sure there is enough flexibility to abide by _semver_

**Comment by yowainwright** [comment]
@samselikoff RE: `v1.x`: yes (stability), no breaking changes. Noted, regarding automated changelogs.

@snewcomer RE: auto-changelogs: yes, [auto-changelog](https://github.com/dollarshaveclub/stickybits/blob/master/package.json#L14-L20) scripts update for all version publishes.

**Pull request merged**
