### PR TITLE
Fastboot compatibility

### PR DESCRIPTION
**Pull request by arjansingh**
@bennycwong

### CODE REVIEW

**Comment by rwwagner90** [comment]
Definitely need fastboot compatibility!

**Comment by rwwagner90** [comment]
@arjansingh any idea why the tests are failing for 1.13? Is that all that is being waited on before merging? Would love to see this merged 😄

**Comment by arjansingh** [comment]
@rwwagner90 fixed. @bennycwong review please?

**Comment by rwwagner90** [comment]
@arjansingh looks like you need some travis.yml updates to use Chrome. You'll need this before_install:

```yml
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version
```

You'll also need:

```yml
sudo: required
dist: trusty
```

**Comment by arjansingh** [comment]
@bennycwong alright we can publish this guy now

**Comment by rwwagner90** [comment]
Thanks @arjansingh! Let me know when the new version is published please 😄

**Comment by bennycwong** [comment]
@briangonzalez needs to be the one to publish.

**Comment by kpfefferle** [comment]
@rwwagner90 @bennycwong I believe this has been released on NPM as 0.0.6. At least that's what we've switched over to using since the PR is closed 👍

**Pull request merged**
